### ISSUE TITLE
Schema Indexes

### ISSUE THREAD

**Issue by LuisMoralesAlonso** [jexp/batch-import#80]
Will schema indexes be supported in the near future?

**Comment by halflings** [comment]
+1 to this.
Would it be possible to support the creation of indexes with this tool?
Creating an index after the tool has finished is not very efficient: the indexes are apparently "created in the background" which in my case is more like "they'll exist one day... maybe." since I've been waiting for quite a while, and my queries are still extremely slow.

**Comment by jexp** [comment]
It works fine to create indexes and constraints with neo4j-shell. 
You can use "schema await" for the index creation to finish.

The batch inserter API is not faster creating those indexes. And going forward more and more of the functionality of this tool will be handled by `neo4j-import`. Including index-creation.

So I am not keen investing work into that feature. Sorry :)
